name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  publishgodev:
    runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-go@v5
    with:
      go-version: '1.22.x'
  - run: GOPROXY=proxy.golang.org go list -m github.com/configurature@${{ github.ref_name }}
